#include "manifest_store.h"
#include "autostart.h"
#include "sha256.h"
#include <algorithm>
#include <bcrypt.h>
#include <cstring>
#include <fstream>
namespace ttr::host {namespace{bool Same(const ModuleIdentityV1&a,const ModuleIdentityV1&b){return _stricmp(a.baseName,b.baseName)==0&&a.timeDateStamp==b.timeDateStamp&&a.sizeOfImage==b.sizeOfImage&&a.pdbAge==b.pdbAge&&std::memcmp(a.pdbGuid.value,b.pdbGuid.value,16)==0;}
bool ReadBounded(const std::wstring&path,std::vector<std::byte>&out,size_t limit){std::ifstream f(path,std::ios::binary);if(!f)return false;f.seekg(0,std::ios::end);auto n=f.tellg();f.seekg(0);if(n<=0||n>static_cast<std::streamoff>(limit))return false;out.resize(static_cast<size_t>(n));f.read(reinterpret_cast<char*>(out.data()),n);return !!f;}
bool Verify(std::span<const std::byte>data,std::span<const std::byte>signature){auto resource=FindResourceW(nullptr,MAKEINTRESOURCEW(102),RT_RCDATA);if(!resource)return false;auto loaded=LoadResource(nullptr,resource);if(!loaded)return false;auto*key=static_cast<PUCHAR>(LockResource(loaded));DWORD keyBytes=SizeofResource(nullptr,resource);if(!key||keyBytes<sizeof(BCRYPT_ECCKEY_BLOB)||signature.size()!=64)return false;Sha256 digest{};if(!Sha256Bytes(data,digest))return false;BCRYPT_ALG_HANDLE algorithm{};BCRYPT_KEY_HANDLE publicKey{};bool ok=false;if(BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_ECDSA_P256_ALGORITHM,nullptr,0)>=0&&BCryptImportKeyPair(algorithm,nullptr,BCRYPT_ECCPUBLIC_BLOB,&publicKey,key,keyBytes,0)>=0)ok=BCryptVerifySignature(publicKey,nullptr,reinterpret_cast<PUCHAR>(digest.data()),static_cast<ULONG>(digest.size()),reinterpret_cast<PUCHAR>(const_cast<std::byte*>(signature.data())),static_cast<ULONG>(signature.size()),0)>=0;if(publicKey)BCryptDestroyKey(publicKey);if(algorithm)BCryptCloseAlgorithmProvider(algorithm,0);return ok;}}
bool ManifestStore::Load(std::string&e)noexcept{auto base=ApplicationDataDirectory()+L"\\compat\\compat";std::vector<std::byte>candidate,signature;if(ReadBounded(base+L".bin",candidate,kMaxManifestBytes)&&ReadBounded(base+L".sig",signature,256)&&Verify(candidate,signature))bytes_=std::move(candidate);if(bytes_.empty()){bytes_.resize(sizeof(ManifestHeaderV1));auto*h=reinterpret_cast<ManifestHeaderV1*>(bytes_.data());std::memcpy(h->magic,kManifestMagic,8);h->formatVersion=kManifestVersion;h->headerSize=sizeof(*h);h->totalSize=sizeof(*h);h->sequence=0;h->recordCount=0;h->recordTableOffset=sizeof(*h);}return ParseManifest(bytes_,view_,e);}
std::span<const std::byte>ManifestStore::SelectedRecordBlob(const std::vector<PeIdentity>&loaded,std::uint64_t&id)const noexcept{id=0;for(const auto&r:view_.records){auto expected=RecordModules(view_,r);std::vector<const PeIdentity*>matched(expected.size());bool all=true;for(size_t index=0;index<expected.size();++index){auto found=std::find_if(loaded.begin(),loaded.end(),[&](const PeIdentity&p){return Same(expected[index],p.identity);});if(found==loaded.end()){all=false;break;}matched[index]=&*found;}if(!all)continue;for(const auto&symbol:RecordSymbols(view_,r)){if(symbol.moduleIndex>=matched.size()||!ValidateSymbolRva(*matched[symbol.moduleIndex],symbol.rva,static_cast<SymbolKind>(symbol.kind))){all=false;break;}}if(all){id=r.recordId;return view_.bytes;}}return{};} }
