#include "manifest_update.h"
#include "autostart.h"
#include "sha256.h"
#include "ttr_manifest.h"
#include "ttr_version.h"
#include <Windows.h>
#include <bcrypt.h>
#include <filesystem>
#include <thread>
#include <vector>
#include <winhttp.h>

namespace ttr::host {
namespace {
bool Download(const std::wstring&url,size_t limit,std::vector<std::byte>&out){URL_COMPONENTS parts{sizeof(parts)};wchar_t host[256]{},path[2048]{};parts.lpszHostName=host;parts.dwHostNameLength=static_cast<DWORD>(std::size(host));parts.lpszUrlPath=path;parts.dwUrlPathLength=static_cast<DWORD>(std::size(path));if(!WinHttpCrackUrl(url.c_str(),0,0,&parts))return false;HINTERNET session=WinHttpOpen(L"TaskbarThumbnailReorder/0.1",WINHTTP_ACCESS_TYPE_AUTOMATIC_PROXY,WINHTTP_NO_PROXY_NAME,WINHTTP_NO_PROXY_BYPASS,0);if(!session)return false;WinHttpSetTimeouts(session,5000,5000,5000,5000);HINTERNET connection=WinHttpConnect(session,host,parts.nPort,0);HINTERNET request=connection?WinHttpOpenRequest(connection,L"GET",path,nullptr,WINHTTP_NO_REFERER,WINHTTP_DEFAULT_ACCEPT_TYPES,parts.nScheme==INTERNET_SCHEME_HTTPS?WINHTTP_FLAG_SECURE:0):nullptr;bool ok=request&&WinHttpSendRequest(request,WINHTTP_NO_ADDITIONAL_HEADERS,0,WINHTTP_NO_REQUEST_DATA,0,0,0)&&WinHttpReceiveResponse(request,nullptr);while(ok){DWORD available{};if(!WinHttpQueryDataAvailable(request,&available)){ok=false;break;}if(!available)break;if(available>limit-out.size()){ok=false;break;}auto previous=out.size();out.resize(previous+available);DWORD read{};if(!WinHttpReadData(request,out.data()+previous,available,&read)){ok=false;break;}out.resize(previous+read);}if(request)WinHttpCloseHandle(request);if(connection)WinHttpCloseHandle(connection);WinHttpCloseHandle(session);return ok&&!out.empty();}
bool Verify(std::span<const std::byte>data,std::span<const std::byte>signature){auto resource=FindResourceW(nullptr,MAKEINTRESOURCEW(102),RT_RCDATA);if(!resource||signature.size()!=64)return false;auto loaded=LoadResource(nullptr,resource);if(!loaded)return false;auto*key=static_cast<PUCHAR>(LockResource(loaded));DWORD keyBytes=SizeofResource(nullptr,resource);if(!key||keyBytes<sizeof(BCRYPT_ECCKEY_BLOB))return false;Sha256 hash{};if(!Sha256Bytes(data,hash))return false;BCRYPT_ALG_HANDLE algorithm{};BCRYPT_KEY_HANDLE publicKey{};bool ok=false;if(BCryptOpenAlgorithmProvider(&algorithm,BCRYPT_ECDSA_P256_ALGORITHM,nullptr,0)>=0&&BCryptImportKeyPair(algorithm,nullptr,BCRYPT_ECCPUBLIC_BLOB,&publicKey,key,keyBytes,0)>=0)ok=BCryptVerifySignature(publicKey,nullptr,reinterpret_cast<PUCHAR>(hash.data()),static_cast<ULONG>(hash.size()),reinterpret_cast<PUCHAR>(const_cast<std::byte*>(signature.data())),static_cast<ULONG>(signature.size()),0)>=0;if(publicKey)BCryptDestroyKey(publicKey);if(algorithm)BCryptCloseAlgorithmProvider(algorithm,0);return ok;}
bool Write(const std::wstring&path,std::span<const std::byte>data){HANDLE file=CreateFileW(path.c_str(),GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if(file==INVALID_HANDLE_VALUE)return false;DWORD written{};bool ok=WriteFile(file,data.data(),static_cast<DWORD>(data.size()),&written,nullptr)&&written==data.size()&&FlushFileBuffers(file);CloseHandle(file);return ok;}
}
void ShowCompatibilityUpdateInfo(HWND owner)noexcept{if(!*TTR_MANIFEST_URL_W){MessageBoxW(owner,L"No compatibility update endpoint is configured in this build. The application will not download unsigned offset data.",L"Taskbar Thumbnail Reorder",MB_OK|MB_ICONINFORMATION);return;}std::thread([owner]{std::vector<std::byte>manifest,signature;std::wstring url=TTR_MANIFEST_URL_W;bool ok=Download(url,kMaxManifestBytes,manifest)&&Download(url+L".sig",256,signature);ManifestView view;std::string error;if(ok)ok=ParseManifest(manifest,view,error)&&Verify(manifest,signature);if(ok){auto directory=ApplicationDataDirectory()+L"\\compat";std::error_code ec;std::filesystem::create_directories(directory,ec);auto manifestTemp=directory+L"\\compat.bin.new",signatureTemp=directory+L"\\compat.sig.new";ok=!ec&&Write(manifestTemp,manifest)&&Write(signatureTemp,signature)&&MoveFileExW(signatureTemp.c_str(),(directory+L"\\compat.sig").c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH)&&MoveFileExW(manifestTemp.c_str(),(directory+L"\\compat.bin").c_str(),MOVEFILE_REPLACE_EXISTING|MOVEFILE_WRITE_THROUGH);if(!ok){DeleteFileW(manifestTemp.c_str());DeleteFileW(signatureTemp.c_str());}}MessageBoxW(owner,ok?L"A verified compatibility manifest was installed. Toggle the feature off and on to apply it.":L"No valid signed compatibility update could be installed.",L"Taskbar Thumbnail Reorder",MB_OK|(ok?MB_ICONINFORMATION:MB_ICONWARNING));}).detach();}
}
