#include "payload_state.h"
#include "classic_backend.h"
#include "xaml_backend.h"
#include <cstring>

namespace ttr::payload {namespace {State state;
void SetResult(PayloadState s,PayloadError e=PayloadError::None){InterlockedExchange(&state.control->payloadError,static_cast<LONG>(e));InterlockedExchange(&state.control->payloadState,static_cast<LONG>(s));}
}
State&GetState()noexcept{return state;}
bool EnsureSession()noexcept{if(state.control)return true;wchar_t name[96]{};swprintf_s(name,L"Local\\TaskbarThumbnailReorder.Session.%lu",GetCurrentProcessId());state.mapping=OpenFileMappingW(FILE_MAP_ALL_ACCESS,FALSE,name);if(!state.mapping)return false;state.view=MapViewOfFile(state.mapping,FILE_MAP_ALL_ACCESS,0,0,kSessionMappingBytes);if(!state.view)return false;auto*c=static_cast<TtrSessionControlV1*>(state.view);if(std::memcmp(c->magic,kSessionMagic,8)||c->byteSize!=sizeof(*c)||c->protocolVersion!=kProtocolVersion||c->explorerPid!=GetCurrentProcessId()||!c->hostPid||!c->sessionNonce||!CheckedRange(c->manifestOffset,c->manifestSize,kSessionMappingBytes)||!CheckedRange(c->logOffset,c->logSize,kSessionMappingBytes)){UnmapViewOfFile(state.view);CloseHandle(state.mapping);state.view=nullptr;state.mapping=nullptr;return false;}HANDLE host=OpenProcess(PROCESS_QUERY_LIMITED_INFORMATION,FALSE,c->hostPid);if(!host){UnmapViewOfFile(state.view);CloseHandle(state.mapping);state.view=nullptr;state.mapping=nullptr;return false;}CloseHandle(host);state.control=c;return true;}
void MarkFault(PayloadError e)noexcept{state.enabled=false;state.faulted=true;if(state.control)SetResult(PayloadState::Faulted,e);}
void ProcessCommand()noexcept{if(!EnsureSession())return;LONG sequence=InterlockedCompareExchange(&state.control->commandSequence,0,0);if(sequence==state.lastCommand)return;state.lastCommand=sequence;auto command=static_cast<Command>(InterlockedCompareExchange(&state.control->command,0,0));switch(command){case Command::Initialize:{SetResult(PayloadState::Initializing);auto*b=static_cast<const std::byte*>(state.view)+state.control->manifestOffset;if(!ResolveCompatibility({b,state.control->manifestSize},state.compatibility))SetResult(PayloadState::Unsupported,PayloadError::UnsupportedModules);else SetResult(PayloadState::Disabled);break;}case Command::Enable:{if(state.faulted.load()){SetResult(PayloadState::Faulted,PayloadError::InternalError);break;}bool classic=false,xaml=false;if(state.compatibility.backendFlags&BackendXaml)xaml=EnableXaml(state.compatibility);if(!xaml&&(state.compatibility.backendFlags&BackendClassic))classic=EnableClassic(state.compatibility);if(classic||xaml){state.enabled=true;SetResult(PayloadState::Active);InterlockedExchange(&state.control->activeThumbnailBackend,xaml?static_cast<LONG>(Backend::Xaml):static_cast<LONG>(Backend::Classic));}else MarkFault(PayloadError::HookCreateFailed);break;}case Command::Disable:case Command::PrepareUnload:{state.enabled=false;ULONGLONG start=GetTickCount64();while(state.activeCallbacks.load()!=0&&GetTickCount64()-start<200)SwitchToThread();if(state.activeCallbacks.load()!=0){MarkFault(PayloadError::CallbackDrainTimeout);break;}DisableClassic();DisableXaml();SetResult(command==Command::PrepareUnload?PayloadState::Unloading:PayloadState::Disabled);break;}case Command::QueryStatus:case Command::SetDebugLogging:case Command::None:break;}InterlockedExchange(&state.control->acknowledgedSequence,sequence);}
}
